// SPDX-License-Identifier: AGPL-3.0-or-later
// Interface text in English and Traditional Chinese (Hong Kong). Every key must exist in
// both languages (unit-tested). `{name}` placeholders are filled by t().

export type Locale = 'en' | 'zh-HK';

const S = {
  'app.tagline': [
    'Free, offline dictation and spelling practice.',
    '免費、可離線的默書及串字練習。',
  ],
  'app.skip': ['Skip to content', '跳到主要內容'],
  'settings.lang': ['Language', '語言'],
  'settings.theme': ['Theme', '主題'],
  'settings.light': ['Light', '淺色'],
  'settings.dark': ['Dark', '深色'],
  'settings.large': ['Large text', '大字'],
  'settings.remote': ['Allow online voices', '容許網上語音'],
  'settings.remoteHelp': [
    'Off by default: online voices send the words to your browser’s speech service.',
    '預設關閉：網上語音會把詞語傳送到瀏覽器的語音服務。',
  ],
  'nav.home': ['My lists', '我的詞表'],
  'nav.review': ['Today’s review ({n})', '今日要溫（{n}）'],
  'home.title': ['My word lists', '我的詞表'],
  'home.empty': [
    'No lists yet. Make one, import a file or add the samples.',
    '未有詞表。可以新增、匯入檔案或加入示範詞表。',
  ],
  'home.new': ['New list', '新增詞表'],
  'home.import': ['Import CSV / TSV / JSON', '匯入 CSV／TSV／JSON'],
  'home.exportAll': ['Back up everything (JSON)', '備份全部（JSON）'],
  'persist.persisted': [
    'Storage: kept — the browser will not clear this data by itself.',
    '儲存：已設為保留，瀏覽器不會自行清除這些資料。',
  ],
  'persist.not-persisted': [
    'Storage: not kept — the browser may clear this data when the device is low on space. Save backups regularly.',
    '儲存：未設為保留，裝置空間不足時瀏覽器可能清除這些資料。請定期備份。',
  ],
  'persist.unsupported': [
    'Storage: this browser cannot be asked to keep the data. Save backups regularly.',
    '儲存：這個瀏覽器不支援「保留資料」，請定期備份。',
  ],
  'persist.ask': ['Ask the browser again', '再向瀏覽器要求'],
  'backup.saved': [
    'Backup file saved ({n} recordings included). Keep it somewhere safe.',
    '已儲存備份檔（包括 {n} 段錄音），請放在安全的地方。',
  ],
  'backup.reminder': [
    'You have {n} changes since your last backup. A backup file protects your lists and recordings if this browser’s data is cleared.',
    '自上次備份後有 {n} 項改動。備份檔可以在瀏覽器資料被清除時保住你的詞表及錄音。',
  ],
  'backup.now': ['Back up now', '立即備份'],
  'backup.later': ['Not now', '稍後'],
  'backup.recRestored': ['{n} recording(s) restored.', '已還原 {n} 段錄音。'],
  'backup.last': ['Last backup from this device: {d}', '此裝置上次備份：{d}'],
  'backup.never': ['No backup saved from this device yet.', '此裝置未曾備份。'],
  'share.title': ['Shared word list', '分享的詞表'],
  'share.note': [
    'The list is inside the link itself (after #), so it is never sent to any server. Recordings and results are not included.',
    '詞表內容就在連結本身（# 之後），不會傳送到任何伺服器。不包括錄音及成績。',
  ],
  'share.add': ['Add to my lists', '加到我的詞表'],
  'share.copy': ['Copy share link', '複製分享連結'],
  'share.copied': ['Share link copied.', '已複製分享連結。'],
  'share.copyYourself': ['Copy the link below.', '請複製下面的連結。'],
  'share.link': ['Share link', '分享連結'],
  'share.qrAlt': ['QR code of the share link for {name}', '「{name}」分享連結的 QR 碼'],
  'share.qrHelp': [
    'Scan with a phone camera to open this list. The code is made on this device.',
    '用手機相機掃描即可開啟這個詞表。QR 碼在這部裝置上產生。',
  ],
  'share.qrDense': [
    'This list makes a large, dense code: print it big or send the link instead.',
    '這個詞表的 QR 碼很密：請放大列印，或改為傳送連結。',
  ],
  'share.qrTooLong': [
    'This list is too long for a QR code; send the link or a file instead.',
    '這個詞表太長，不能做成 QR 碼；請傳送連結或檔案。',
  ],
  'share.qrSave': ['Save QR code (.svg)', '儲存 QR 碼（.svg）'],
  'nav.voices': ['Voices', '語音'],
  'nav.class': ['Class', '班級'],
  'class.title': ['Class lists by file', '用檔案派發詞表'],
  'class.intro': [
    'No accounts and no server: lists and results travel as files, sent the way your school already sends files (email, school platform, USB stick).',
    '無需帳戶，亦無伺服器：詞表及成績以檔案往來，用學校現有的方法傳送（電郵、學校平台、USB 手指）。',
  ],
  'class.chooseLists': ['Lists', '詞表'],
  'class.noLists': ['There are no lists on this device yet.', '這部裝置暫時未有詞表。'],
  'class.pickOne': ['Choose at least one list.', '請最少選擇一個詞表。'],
  'class.sendTitle': ['Teachers: send lists to a class', '老師：派詞表給全班'],
  'class.sendHelp': [
    'Choose lists, give the pack a title and save the file. Recordings and results are not included. Send the same lists again later with changes, and pupils’ copies are updated.',
    '選擇詞表，為詞表包加上標題，然後儲存檔案。不包括錄音及成績。之後修改再派發，學生的詞表會更新。',
  ],
  'class.packTitle': [
    'Title (for example “P.3 Week 5 dictation”)',
    '標題（例如「三年級第 5 週默書」）',
  ],
  'class.packNote': ['Note for pupils (optional)', '給學生的備註（可選）'],
  'class.packSave': ['Save class pack (.json)', '儲存詞表包（.json）'],
  'class.packSaved': ['Saved a class pack with {n} list(s).', '已儲存詞表包，共 {n} 個詞表。'],
  'class.openTitle': ['Pupils: open a class pack', '學生：開啟詞表包'],
  'class.openHelp': [
    'Open the file from your teacher. You will see what changes before anything is saved.',
    '開啟老師給你的檔案。儲存前會先顯示有甚麼改變。',
  ],
  'class.openPack': ['Open class pack', '開啟詞表包'],
  'class.willAdd': ['New lists: {names}', '新詞表：{names}'],
  'class.willUpdate': ['Lists to update: {names}', '會更新的詞表：{names}'],
  'class.unchanged': ['Already up to date: {names}', '已是最新：{names}'],
  'class.apply': ['Add and update these lists', '加入及更新這些詞表'],
  'class.cancel': ['Cancel', '取消'],
  'class.applied': [
    'Added {added} and updated {updated} list(s).',
    '已加入 {added} 個、更新 {updated} 個詞表。',
  ],
  'class.resultsTitle': ['Pupils: send results to your teacher', '學生：把成績交給老師'],
  'class.resultsHelp': [
    'The file holds how many answers were right, wrong or blank in each practice and which words were missed. What you typed is not included.',
    '檔案只包括每次練習對、錯及漏空的數目，以及默錯的詞語；不包括你輸入的內容。',
  ],
  'class.pupilName': ['Your name (as your teacher knows you)', '你的名字（老師認得的寫法）'],
  'class.resultsSave': ['Save results file (.json)', '儲存成績檔（.json）'],
  'class.resultsSaved': [
    'Results file saved. Send it to your teacher.',
    '已儲存成績檔，請交給老師。',
  ],
  'class.readTitle': ['Teachers: read results files', '老師：查看成績檔'],
  'class.readHelp': [
    'Open many results files at once. The summary is made on this device and is not saved.',
    '可一次開啟多個成績檔。摘要只在這部裝置上計算，不會儲存。',
  ],
  'class.honesty': [
    'Results files are made on pupils’ devices and can be edited: use them to see which words need practice, not for marks.',
    '成績檔由學生的裝置產生，可以被修改：只適合用來找出要多練習的詞語，不應用作評分。',
  ],
  'class.openResults': ['Open results files', '開啟成績檔'],
  'class.summaryPupils': ['{n} pupil(s).', '共 {n} 位學生。'],
  'class.summaryReplaced': [
    '{n} older file(s) of the same pupil were left out.',
    '已略過同一學生較舊的 {n} 個檔案。',
  ],
  'class.summaryTried': [
    '{tried} of {n} tried; {all} had every word right last time.',
    '{n} 人中 {tried} 人練習過；{all} 人最近一次全對。',
  ],
  'class.colPupil': ['Pupil', '學生'],
  'class.colTries': ['Tries', '次數'],
  'class.colBest': ['Best', '最佳'],
  'class.colLast': ['Last', '最近'],
  'class.missed': ['Most missed:', '最多人默錯：'],
  'class.missedWord': ['{text} ({n})', '{text}（{n}）'],
  'class.summaryCsv': ['Save summary (.csv)', '儲存摘要（.csv）'],
  'voices.title': ['Voices on this device', '此裝置的語音'],
  'voices.intro': [
    'Try each voice, then choose the one to use for its language. Online voices send the words to your browser’s speech service and can only be tried when allowed in settings.',
    '可以逐個試聽，再選定每種語言用哪個語音。網上語音會把詞語傳送到瀏覽器的語音服務，要在設定中容許才可試聽。',
  ],
  'voices.none': [
    'This browser offers no voices. Record the words yourself, or read them aloud.',
    '這個瀏覽器沒有提供語音。請自己錄音，或由家長讀出。',
  ],
  'voices.name': ['Voice', '語音'],
  'voices.lang': ['Language', '語言'],
  'voices.where': ['Where', '位置'],
  'voices.local': ['On this device', '本機'],
  'voices.online': ['Online', '網上'],
  'voices.try': ['Try', '試聽'],
  'voices.use': ['Use for this language', '用於這種語言'],
  'voices.inUse': ['In use', '使用中'],
  'voices.chosen': ['“{name}” will be used for its language.', '這種語言會使用「{name}」。'],
  'voices.cleared': ['Back to the automatic choice.', '已改回自動選擇。'],
  'home.samples': ['Add sample lists', '加入示範詞表'],
  'home.wipe': ['Delete all data on this device', '刪除此裝置上的所有資料'],
  'home.wipeConfirm': [
    'Delete every list, result and recording on this device? This cannot be undone.',
    '刪除此裝置上所有詞表、成績及錄音？此操作無法復原。',
  ],
  'home.items': ['{n} items', '{n} 項'],
  'home.due': ['{n} due', '{n} 項要溫'],
  'home.open': ['Edit', '編輯'],
  'home.practise': ['Practise', '練習'],
  'home.imported': ['Imported {n} list(s).', '已匯入 {n} 個詞表。'],
  'home.importedCsv': ['Imported {n} words into “{name}”.', '已匯入 {n} 個詞語至「{name}」。'],
  'home.skipped': ['Skipped empty rows: {rows}.', '已略過空行：{rows}。'],
  'home.backupNote': [
    'A backup file contains your lists, results, review schedule and recordings. Files from v0.1 (without recordings) can still be imported.',
    '備份檔包括詞表、成績、溫習時間表及錄音。v0.1 的備份檔（沒有錄音）仍然可以匯入。',
  ],
  'list.name': ['List name', '詞表名稱'],
  'list.subject': ['Subject', '科目'],
  'subject.english': ['English', '英文'],
  'subject.chinese': ['Chinese (Cantonese)', '中文（粵語）'],
  'subject.mandarin': ['Mandarin', '普通話'],
  'subject.other': ['Other', '其他'],
  'list.lang': ['Reading language', '讀音語言'],
  'lang.en-GB': ['English (UK)', '英文（英式）'],
  'lang.en-US': ['English (US)', '英文（美式）'],
  'lang.yue-HK': ['Cantonese (Hong Kong)', '粵語（香港）'],
  'lang.zh-TW': ['Mandarin (Traditional)', '普通話（繁體）'],
  'lang.zh-Hans-CN': ['Mandarin (Simplified)', '普通話（簡體）'],
  'list.add': ['Add words (one per line)', '加入詞語（每行一個）'],
  'list.addBtn': ['Add', '加入'],
  'list.word': ['Word or sentence', '詞語或句子'],
  'list.accept': ['Also accept (separate with |)', '其他可接受答案（以 | 分隔）'],
  'list.note': ['Note', '備註'],
  'list.say': ['Read as (optional)', '讀出文字（可不填）'],
  'list.sayHelp': [
    '“Read as” changes only what the voice says, e.g. a word with the same sound when a device voice reads a character the wrong way. Marking always uses the word itself.',
    '「讀出文字」只改變語音讀出的內容，例如裝置語音把多音字讀錯時，可以填一個同音字。批改永遠以詞語本身為準。',
  ],
  'list.itemLang': ['Language', '語言'],
  'list.sameAsList': ['Same as list', '跟詞表'],
  'list.recording': ['Recording', '錄音'],
  'list.record': ['Record', '錄音'],
  'list.stop': ['Stop', '停止'],
  'list.play': ['Play', '播放'],
  'list.deleteRec': ['Delete recording', '刪除錄音'],
  'list.deleteItem': ['Delete', '刪除'],
  'list.duplicate': ['Duplicate', '重複'],
  'list.save': ['Saved on this device.', '已儲存於此裝置。'],
  'list.exportCsv': ['Export CSV', '匯出 CSV'],
  'list.delete': ['Delete list', '刪除詞表'],
  'list.deleteConfirm': ['Delete this list and its recordings?', '刪除此詞表及其錄音？'],
  'list.back': ['Back to my lists', '返回我的詞表'],
  'list.items': ['Words', '詞語'],
  'list.recordingNow': ['Recording… (stops by itself after {n} s)', '錄音中……（{n} 秒後自動停止）'],
  'list.recSaved': ['Recording saved on this device.', '錄音已儲存於此裝置。'],
  'list.full': ['A list can hold at most {n} items.', '每個詞表最多 {n} 項。'],
  'voice.exact': ['Device voice: {name}', '裝置語音：{name}'],
  'voice.mismatch': [
    'No voice for this language on this device; using {name} ({lang}) instead. Recording the words is better.',
    '此裝置沒有這種語言的語音，暫用 {name}（{lang}）代替。建議自己錄音。',
  ],
  'voice.none': [
    'No device voice for this language. Record the words, or read them aloud yourself.',
    '此裝置沒有這種語言的語音。請錄音，或由家長讀出。',
  ],
  'voice.remoteSkipped': [
    'Only online voices exist for this language; allow them in settings if you accept that.',
    '這種語言只有網上語音；如接受，可在設定中容許。',
  ],
  'voice.help': ['How to add a Cantonese voice', '如何加入粵語語音'],
  'practice.title': ['Practise: {name}', '練習：{name}'],
  'practice.mode': ['How', '方式'],
  'mode.paper': ['On paper (mark afterwards)', '紙上默書（之後批改）'],
  'mode.typing': ['Type the answers (automatic marking)', '打字作答（自動批改）'],
  'mode.cards': ['Flash cards (mark yourself)', '溫習卡（自己評分）'],
  'practice.shuffle': ['Shuffle', '調亂次序'],
  'practice.seed': ['Shuffle number (same number = same order)', '洗牌號碼（同一號碼＝同一次序）'],
  'practice.repeats': ['Readings per item', '每項讀幾次'],
  'practice.gap': ['Seconds between readings', '每次之間停幾秒'],
  'practice.itemGap': ['Seconds between items', '每項之間停幾秒'],
  'practice.countdown': ['Countdown (s)', '開始前倒數（秒）'],
  'practice.rate': ['Speed', '語速'],
  'practice.hide': ['Hide the words while reading', '讀出時隱藏詞語'],
  'practice.punct': ['Read punctuation aloud', '讀出標點'],
  'practice.from': ['Start from item', '由第幾項開始'],
  'practice.passage': [
    'Passage mode: read each sentence part separately (split at punctuation)',
    '段落模式：按標點分句，逐句讀出',
  ],
  'practice.punctNames': ['Names for punctuation marks', '標點讀法'],
  'practice.punctNamesHelp': [
    'One per line, “mark = name”. These replace the built-in names when punctuation is read aloud.',
    '每行一個，格式「標點 = 讀法」。讀出標點時會取代內置讀法。',
  ],
  'practice.start': ['Start', '開始'],
  'practice.invalid': [
    'Please check the numbers: readings 1–5, gaps 0–20 / 0–60 s, countdown 0–10 s, speed 0.5–1.5, shuffle number 0–999999.',
    '請檢查數字：每項讀 1–5 次、停頓 0–20／0–60 秒、倒數 0–10 秒、語速 0.5–1.5、洗牌號碼 0–999999。',
  ],
  'run.counter': ['Item {i} of {n}', '第 {i} 項，共 {n} 項'],
  'run.part': ['part {i} of {n}', '第 {i} 句，共 {n} 句'],
  'run.countdown': ['Starting in {s}…', '{s} 秒後開始……'],
  'run.speaking': ['Reading…', '讀出中……'],
  'run.waiting': ['Write it down…', '請寫下來……'],
  'run.paused': ['Paused', '已暫停'],
  'run.pause': ['Pause', '暫停'],
  'run.resume': ['Resume', '繼續'],
  'run.prev': ['Previous', '上一項'],
  'run.next': ['Next', '下一項'],
  'run.repeat': ['Read again', '重讀'],
  'run.stop': ['Finish', '完成'],
  'run.show': ['Show word', '顯示詞語'],
  'run.hidden': ['(hidden)', '（已隱藏）'],
  'run.readDone': ['I have read it aloud', '我已讀出'],
  'run.answer': ['Your answer', '你的答案'],
  'run.answerHint': ['Press Enter for the next item.', '按 Enter 到下一項。'],
  'cards.read': ['Read aloud', '讀出'],
  'cards.reveal': ['Show answer', '顯示答案'],
  'cards.right': ['I got it right', '我答對了'],
  'cards.wrong': ['I got it wrong', '我答錯了'],
  'results.title': ['Results', '成績'],
  'results.score': ['{r} of {n} right', '{n} 項中答對 {r} 項'],
  'results.right': ['Right', '對'],
  'results.wrong': ['Wrong', '錯'],
  'results.blank': ['Not answered', '未作答'],
  'results.expected': ['Answer', '答案'],
  'results.yours': ['Typed', '作答'],
  'results.markHint': ['Mark each item, then save.', '逐項批改，然後儲存。'],
  'results.autoNote': [
    'Automatic marking is only a guide; you can change any mark. Chinese is compared character by character.',
    '自動批改只供參考，可以修改任何一項。中文會逐字比對。',
  ],
  'results.save': ['Save results', '儲存成績'],
  'results.saved': [
    'Saved. Wrong words will come back for review.',
    '已儲存。答錯的詞語會安排重溫。',
  ],
  'results.checkerFailed': [
    'Some answers could not be marked automatically (internal check failed). Please mark them yourself.',
    '部分答案未能自動批改（內部檢查未通過），請自行批改。',
  ],
  'results.again': ['Practise again', '再練習'],
  'results.continue': ['Continue from item {n}', '由第 {n} 項繼續'],
  'results.forgiven': ['Forgiven: {rules}', '已忽略：{rules}'],
  'results.zeroWidth': [
    'Invisible characters were removed from the answer.',
    '已移除答案中的隱形字元。',
  ],
  'results.accepted': ['Accepted answer: {a}', '可接受答案：{a}'],
  'diff.legend': [
    'Green = right, red = wrong letter, struck = extra, ⁁ = missing, ↔ = swapped',
    '綠＝正確，紅＝錯字母，刪除線＝多了，⁁＝漏了，↔＝調轉了',
  ],
  'diff.missing': ['missing “{a}”', '漏了「{a}」'],
  'diff.should': ['should be “{a}”', '應為「{a}」'],
  'diff.extra': ['extra', '多了'],
  'diff.swap': ['swapped', '調轉了'],
  'rule.case': ['capital letters', '大小寫'],
  'rule.quotes': ['curly quotes', '彎引號'],
  'rule.dashes': ['dash type', '連字號類型'],
  'rule.spaces': ['extra spaces', '多餘空格'],
  'rule.fullwidth-alnum': ['full-width letters', '全形英數字'],
  'rule.cjk-punct': ['half-width punctuation', '半形標點'],
  'rule.final-punct': ['final full stop', '句末標點'],
  'rule.zero-width': ['invisible characters', '隱形字元'],
  'rule.nfc': ['accent encoding', '重音符號編碼'],
  'review.title': ['Today’s review', '今日要溫'],
  'review.empty': ['Nothing to review today. Well done!', '今日沒有要溫的詞語，做得好！'],
  'review.box': ['Box {b}', '第 {b} 盒'],
  'review.start': ['Review these', '溫習這些'],
  'footer.privacy': [
    'Your lists, results and recordings stay on this device. No ads, no tracking, no network requests.',
    '詞表、成績及錄音只存於此裝置。沒有廣告、沒有追蹤、不發出網絡請求。',
  ],
  'footer.marking': ['Automatic marking is only a guide.', '自動批改只供參考。'],
  'footer.affiliation': [
    'Independent open-source project, not affiliated with any other dictation or spelling product.',
    '獨立開源項目，與任何其他默書或串字產品並無關連。',
  ],
  'footer.source': ['Source code', '原始碼'],
  'footer.licence': ['Licence: AGPL-3.0-or-later', '授權：AGPL-3.0-or-later'],
  'footer.coffee': ['Buy me a coffee', '請我喝杯咖啡'],
  'home.data': ['Your data', '你的資料'],
  'home.newName': ['New list', '新詞表'],
  'home.wiped': ['All data on this device was deleted.', '已刪除此裝置上的所有資料。'],
  'home.storage': ['Recordings use {mb} MB on this device.', '錄音在此裝置佔用 {mb} MB。'],
  'review.due': ['{n} words to review today.', '今日有 {n} 個詞語要溫。'],
  'print.sheet': ['Print answer sheet', '列印默書紙'],
  'print.key': ['Print answer key', '列印答案'],
  'print.scoreBtn': ['Print score sheet', '列印成績表'],
  'print.sheetTitle': ['Answer sheet', '默書紙'],
  'print.keyTitle': ['Answer key', '答案'],
  'print.scoreTitle': ['Score sheet', '成績表'],
  'print.name': ['Name', '姓名'],
  'print.date': ['Date', '日期'],
  'print.score': ['Score', '分數'],
  'print.mark': ['Mark', '批改'],
  'home.samplesAdded': ['Added {n} sample list(s).', '已加入 {n} 個示範詞表。'],
  'home.samplesThere': ['The sample lists are already here.', '示範詞表已經加入。'],
  'common.cancel': ['Cancel', '取消'],
  'common.close': ['Close', '關閉'],
  'error.unexpected': ['Something went wrong: {msg}', '出現問題：{msg}'],
} as const satisfies Record<string, readonly [string, string]>;

export type StringKey = keyof typeof S;
export const STRINGS: Readonly<Record<StringKey, readonly [string, string]>> = S;

let locale: Locale = 'zh-HK';
export const getLocale = (): Locale => locale;
export const setLocale = (l: Locale): void => {
  locale = l;
};

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  const pair = STRINGS[key];
  const s = pair[locale === 'en' ? 0 : 1];
  return s.replace(/\{(\w+)\}/g, (_, k: string) => String(params[k] ?? `{${k}}`));
}
